### ISSUE TITLE
contribute.md

### ISSUE THREAD

**Issue by rihards** [Coonti/Coonti#10]
I think it would be a good idea to add a contribute.md file so that people would know how to contribute and if there are any specific things to be kept in mind.

There are several good templates out there, for example:
https://github.com/contribute-md/contribute-md-template

**Comment by jannekalliola** [comment]
Added the first version, does this answer at least the most basic questions?

**Comment by rihards** [comment]
I think it looks great already. Can definitely consider this as done.
