### ISSUE TITLE
Errors from event handlers are quietly ignored

### ISSUE THREAD

**Issue by akx** [Coonti/Coonti#3]
When the `cb` for a `fireEventCallback` fails, nothing is done and the error is swallowed.

To be fair, [the TODO comment here](https://github.com/Coonti/Coonti/blob/4ef951ee999f514516726a699a59c7e12e165d69/coonti/core.js#L314) touches upon this -- for a quick "fix", `console.error(err);` should help people debug this.

**Comment by coonti-admin** [comment]
No comments, thus marked as closed
