### ISSUE TITLE
Mismatch in theme name casing

### ISSUE THREAD

**Issue by akx** [Coonti/Coonti#4]
The theme folders under `themes/` are lower-case, but the default configuration expects to find `Seed` (not `seed`).

This is related to #2.

EDIT: after renaming the directory to `Seed`, things still fail, though in a different way, as other parts seem to expect `seed`.

EDIT 2: Symlinking works, but there's a warning: `{"level":"error","message":"TemplateManager - Could not load theme 'seed', as theme with name 'Seed' is already loaded.","timestamp":"2017-05-04T19:34:18.970Z"}
`

**Comment by jannekalliola** [comment]
This should be fixed now. Please retest.

**Comment by akx** [comment]
Seems to be fixed!
